Repository storybookjs/addon-onboarding, pull requests merged in 2023-06, with the labels that each got.

#37 use onboarding parameter in conjunction with onboarding path
  src/App.tsx
  src/manager.tsx
Labels: patch

#41 Change code for Javascript projects
  src/features/WriteStoriesModal/code/javascript.tsx
Labels: patch

#44 Various improvements
  .github/assets/onboarding-intro.png
  MAINTAINERS.md
  README.md
  src/App.tsx
  src/manager.tsx
Labels: patch

#45 Use the correct event to detect args change
  src/features/GuidedTour/GuidedTour.tsx
Labels: patch

#40 Add core server events for telemetry
  .github/workflows/chromatic.yml
  .github/workflows/release.yml
  .storybook/local-preset.js
  .storybook/main.ts
  MAINTAINERS.md
  manager.js
  package.json
  pnpm-lock.yaml
  preset.js
  preview.js
  src/App.tsx
  src/constants.ts
  src/features/WriteStoriesModal/WriteStoriesModal.tsx
  src/preset.ts
  src/preview.ts
  tsup.config.ts
  yarn.lock
Labels: patch

#51 Fixes on syntax highlighter
  src/components/Modal/Modal.styled.tsx
  src/components/SyntaxHighlighter/Snippet/Snippet.styled.tsx
  src/components/SyntaxHighlighter/Snippet/Snippet.tsx
  src/components/SyntaxHighlighter/SyntaxHighlighter.stories.tsx
  src/components/SyntaxHighlighter/SyntaxHighlighter.styled.tsx
  src/components/SyntaxHighlighter/SyntaxHighlighter.tsx
  src/features/WriteStoriesModal/WriteStoriesModal.styled.tsx
  src/features/WriteStoriesModal/WriteStoriesModal.tsx
  src/features/WriteStoriesModal/code/nextjs-typescript.tsx
  src/features/WriteStoriesModal/code/typescript.tsx
Labels: patch

#52 Improve story detection
  src/features/WriteStoriesModal/WriteStoriesModal.tsx
  src/features/WriteStoriesModal/hooks/useGetWarningButtonStatus.tsx
Labels: patch

#53 Fix configure page's layout
  src/stories/Introduction.mdx
Labels: patch

#55 Fix watch mode
  .npmrc
  package.json
  pnpm-lock.yaml
  tsup.config.ts
Labels: skip-release

#62 Pass addon version in telemetry event
  src/preset.ts
Labels: patch

#67 fix links in configure.mdx
  src/stories/Configure.mdx
Labels: skip-release

#70 Release 1.0.0
  auto.config.js
Labels: major

#73 Display the button story filename in tooltip
  src/App.tsx
  src/components/SyntaxHighlighter/Snippet/Snippet.tsx
  src/components/SyntaxHighlighter/SyntaxHighlighter.stories.tsx
  src/components/SyntaxHighlighter/SyntaxHighlighter.tsx
  src/features/GuidedTour/GuidedTour.tsx
  src/features/WriteStoriesModal/WriteStoriesModal.stories.tsx
  src/features/WriteStoriesModal/WriteStoriesModal.tsx
  src/features/WriteStoriesModal/code/javascript.tsx
  src/features/WriteStoriesModal/code/nextjs-typescript.tsx
  src/features/WriteStoriesModal/code/types.ts
  src/features/WriteStoriesModal/code/typescript.tsx
  src/features/WriteStoriesModal/hooks/useGetFrameworkName.tsx
  src/features/WriteStoriesModal/hooks/useGetProject.tsx
Labels: patch
